#!/usr/bin/env python3
"""
Run once to build Tina.app:
    python3 build_app.py

Then launch with:
    open Tina.app
Or drag Tina.app to the Dock for permanent access.
"""
import os
import sys
import subprocess
import shutil
import tempfile
from pathlib import Path

TINA_DIR = Path(__file__).parent.resolve()
APP_PATH = TINA_DIR / "Tina.app"
ICON_SRC = Path("/Users/sameedahmed/Desktop/tina1.png")


PY_FILES = ["app.py", "monitor.py", "detector.py", "reporter.py",
            "obsidian.py", "folder_tracker.py", "ai_monitor.py",
            "persistence.py", "wake_monitor.py", "main.py"]


def build():
    if APP_PATH.exists():
        shutil.rmtree(APP_PATH)

    macos_dir     = APP_PATH / "Contents" / "MacOS"
    resources_dir = APP_PATH / "Contents" / "Resources"
    macos_dir.mkdir(parents=True)
    resources_dir.mkdir(parents=True)

    # Copy Python source into Resources (avoids TCC restrictions on ~/Documents)
    for name in PY_FILES:
        src = TINA_DIR / name
        if src.exists():
            shutil.copy2(src, resources_dir / name)
            print(f"   Copied {name}")

    # Bundle dependencies so the unsigned app can load C extensions
    print("   Installing dependencies into bundle…")
    subprocess.run([
        sys.executable, "-m", "pip", "install",
        "psutil", "Pillow",
        "--target", str(resources_dir),
        "--quiet", "--upgrade",
    ], check=True)
    print("   Dependencies bundled  ✓")

    _write_launcher(macos_dir / "Tina", resources_dir)
    _write_plist(APP_PATH / "Contents" / "Info.plist")
    _write_icns(ICON_SRC, resources_dir / "tina.icns")

    subprocess.run(["killall", "Dock"], check=False, capture_output=True)

    print(f"✓  Built  {APP_PATH}")
    print(f"   Launch: open \"{APP_PATH}\"")
    print(f"   Re-run build_app.py after editing source files.")


def _write_launcher(path: Path, resources: Path):
    import shutil as _sh
    python = (_sh.which("python3")
              or "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3")
    path.write_text(f"""\
#!/bin/bash
# Auto-generated by build_app.py
RESOURCES="{resources}"
exec > "$RESOURCES/tina_launch.log" 2>&1
export PYTHONPATH="$RESOURCES"
cd "$RESOURCES"
# Force arm64 — the Python Framework is a universal binary; the bundle
# launcher may otherwise pick x86_64, which can't load arm64 C extensions.
exec /usr/bin/arch -arm64 "{python}" "$RESOURCES/app.py"
""")
    path.chmod(0o755)


def _write_plist(path: Path):
    path.write_text("""\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>            <string>Tina</string>
  <key>CFBundleDisplayName</key>     <string>Tina</string>
  <key>CFBundleIdentifier</key>      <string>com.tina.devmonitor</string>
  <key>CFBundleVersion</key>         <string>1.0</string>
  <key>CFBundleShortVersionString</key> <string>1.0</string>
  <key>CFBundlePackageType</key>     <string>APPL</string>
  <key>CFBundleExecutable</key>      <string>Tina</string>
  <key>CFBundleIconFile</key>        <string>tina</string>
  <key>NSHighResolutionCapable</key> <true/>
  <key>LSMinimumSystemVersion</key>  <string>10.13</string>
  <key>NSPrincipalClass</key>        <string>NSApplication</string>
  <key>LSUIElement</key>             <false/>
  <key>LSArchitecturePriority</key>
  <array><string>arm64</string><string>x86_64</string></array>
</dict>
</plist>
""")


def _write_icns(src: Path, out: Path):
    if not src.exists():
        print(f"   Warning: icon not found at {src} — skipping")
        return
    try:
        from PIL import Image
        img = Image.open(src).convert("RGBA")

        tmp = Path(tempfile.mkdtemp())
        iconset = tmp / "tina.iconset"
        iconset.mkdir()

        for sz in [16, 32, 64, 128, 256, 512, 1024]:
            img.resize((sz, sz), Image.LANCZOS).save(
                iconset / f"icon_{sz}x{sz}.png")
            if sz <= 512:
                img.resize((sz * 2, sz * 2), Image.LANCZOS).save(
                    iconset / f"icon_{sz}x{sz}@2x.png")

        subprocess.run(
            ["iconutil", "-c", "icns", str(iconset), "-o", str(out)],
            check=True, capture_output=True,
        )
        shutil.rmtree(tmp)
        print(f"   Icon → tina.icns  ✓")
    except Exception as exc:
        print(f"   Warning: icon creation failed — {exc}")


if __name__ == "__main__":
    build()
